site_name: Nuklear-cr
site_url: https://guidipolito.github.io/nuklear-cr/
repo_url: https://github.com/guidipolito/nuklear-cr/
edit_uri: blob/master/docs/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

extra_css:
  - css/mkdocstrings.css
  - css/main.css
extra_javascript:
  - js/main.js

plugins:
  - search
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
      handlers:
        crystal:
          crystal_docs_flags:
            - src/nuklear.cr

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.superfences
  - deduplicate-toc
  - toc:
      permalink: "#"
